name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker on self-hosted runner
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Deploy with Docker Compose
        run: sudo DOCKERHUB_USER="${{ vars.DOCKERHUB_USER }}" docker compose up -d --build