# API keys ,sensitive data, credentials, and other secrets should not be stored in your code repository. This workflow uses the TruffleHog action to scan for secrets in your codebase and alert you if any are found.
# GitLeaks 
name: Secrets Scan



